from app.ai.tools.handoff import HANDOFF_TOOL, HANDOFF_TOOL_NAME
from app.ai.tools.query import (
    LOGISTICS_QUERY_TOOL,
    LOGISTICS_QUERY_TOOL_NAME,
    ORDER_QUERY_TOOL,
    ORDER_QUERY_TOOL_NAME,
    PAYMENT_QUERY_TOOL,
    PAYMENT_QUERY_TOOL_NAME,
)

ALL_TOOLS: list[dict[str, object]] = [
    HANDOFF_TOOL,
    ORDER_QUERY_TOOL,
    PAYMENT_QUERY_TOOL,
    LOGISTICS_QUERY_TOOL,
]

QUERY_TOOL_NAMES: frozenset[str] = frozenset(
    [ORDER_QUERY_TOOL_NAME, PAYMENT_QUERY_TOOL_NAME, LOGISTICS_QUERY_TOOL_NAME]
)

__all__ = [
    "HANDOFF_TOOL",
    "HANDOFF_TOOL_NAME",
    "ORDER_QUERY_TOOL",
    "ORDER_QUERY_TOOL_NAME",
    "PAYMENT_QUERY_TOOL",
    "PAYMENT_QUERY_TOOL_NAME",
    "LOGISTICS_QUERY_TOOL",
    "LOGISTICS_QUERY_TOOL_NAME",
    "ALL_TOOLS",
    "QUERY_TOOL_NAMES",
]
